// <auto-generated />
using System;
using ContactsManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211215210447_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ContactsManager.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee605bb4-4a87-4f4e-b286-a0bb48b4b17b"),
                            City = "Port Sylvia",
                            Country = "Puerto Rico",
                            Email = "Jocelyn93@yahoo.com",
                            FirstName = "Jocelyn",
                            FullName = "Jocelyn Johanna",
                            LastName = "Johanna",
                            Phone = "(421)-910-5548",
                            State = "Louisiana",
                            StreetName = "Ellie Meadow",
                            ZipCode = "92533"
                        },
                        new
                        {
                            Id = new Guid("a25adf3c-7915-442e-b334-8ad434c2e8ce"),
                            City = "Smithammouth",
                            Country = "Monaco",
                            Email = "Jaydon_Bella@yahoo.com",
                            FirstName = "Jaydon",
                            FullName = "Jaydon Bella",
                            LastName = "Bella",
                            Phone = "(825)-416-5760",
                            State = "West Virginia",
                            StreetName = "Cayla Corners",
                            ZipCode = "00019"
                        },
                        new
                        {
                            Id = new Guid("4c00f799-8391-4f36-b874-77f50f0444fa"),
                            City = "North Mable",
                            Country = "Mexico",
                            Email = "Tatyana.Brody@yahoo.com",
                            FirstName = "Tatyana",
                            FullName = "Tatyana Brody",
                            LastName = "Brody",
                            Phone = "(972)-956-0561",
                            State = "Kansas",
                            StreetName = "Naomi Square",
                            ZipCode = "89395-8246"
                        },
                        new
                        {
                            Id = new Guid("e6173ebc-31c0-4753-840b-48cf507ad60e"),
                            City = "Quitzonshire",
                            Country = "Greece",
                            Email = "Jake3@hotmail.com",
                            FirstName = "Jake",
                            FullName = "Jake Rolando",
                            LastName = "Rolando",
                            Phone = "(176)-263-3486",
                            State = "South Carolina",
                            StreetName = "Dee Grove",
                            ZipCode = "55596"
                        },
                        new
                        {
                            Id = new Guid("cd3a0849-231c-4b0e-b8e7-854634e98ca8"),
                            City = "East Laverneburgh",
                            Country = "Montenegro",
                            Email = "Daisy86@yahoo.com",
                            FirstName = "Daisy",
                            FullName = "Daisy Faye",
                            LastName = "Faye",
                            Phone = "(069)-341-2149",
                            State = "New Jersey",
                            StreetName = "Legros Villages",
                            ZipCode = "63110-9501"
                        },
                        new
                        {
                            Id = new Guid("fa035e8b-7ee3-42a8-96d5-38bffee9b93c"),
                            City = "West Kaylahland",
                            Country = "Iceland",
                            Email = "Lessie23@yahoo.com",
                            FirstName = "Lessie",
                            FullName = "Lessie Evie",
                            LastName = "Evie",
                            Phone = "(795)-791-7733",
                            State = "Vermont",
                            StreetName = "Bell Shoals",
                            ZipCode = "54599"
                        },
                        new
                        {
                            Id = new Guid("074f4741-d41f-4058-af2c-2aa253296129"),
                            City = "Lake Norwoodfurt",
                            Country = "Virgin Islands, British",
                            Email = "Thad_Moises@hotmail.com",
                            FirstName = "Thad",
                            FullName = "Thad Moises",
                            LastName = "Moises",
                            Phone = "(208)-626-9720",
                            State = "Wyoming",
                            StreetName = "America Dam",
                            ZipCode = "08229"
                        },
                        new
                        {
                            Id = new Guid("eae05c1c-d450-4220-a495-d95e0f0dc765"),
                            City = "Port Ona",
                            Country = "Honduras",
                            Email = "Kendra.Myra74@gmail.com",
                            FirstName = "Kendra",
                            FullName = "Kendra Myra",
                            LastName = "Myra",
                            Phone = "(993)-272-2011",
                            State = "Ohio",
                            StreetName = "Ed Squares",
                            ZipCode = "36479-1513"
                        },
                        new
                        {
                            Id = new Guid("cb8ddd3b-23b5-411f-b79b-8d013c14cd31"),
                            City = "East Rickie",
                            Country = "Germany",
                            Email = "Ben_Cristian@hotmail.com",
                            FirstName = "Ben",
                            FullName = "Ben Cristian",
                            LastName = "Cristian",
                            Phone = "(460)-402-8378",
                            State = "Mississippi",
                            StreetName = "Estella Prairie",
                            ZipCode = "16964"
                        },
                        new
                        {
                            Id = new Guid("81aeec6d-f8da-4ccd-b23a-0eb8d1c5c508"),
                            City = "Myronmouth",
                            Country = "Norway",
                            Email = "Katelyn64@hotmail.com",
                            FirstName = "Katelyn",
                            FullName = "Katelyn Sabrina",
                            LastName = "Sabrina",
                            Phone = "(008)-855-8647",
                            State = "South Carolina",
                            StreetName = "Schimmel Loop",
                            ZipCode = "60085"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
